// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastball_cpp
Rcpp::List fastball_cpp(Rcpp::List inputList, int numSwaps);
RcppExport SEXP _backbone_fastball_cpp(SEXP inputListSEXP, SEXP numSwapsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputList(inputListSEXP);
    Rcpp::traits::input_parameter< int >::type numSwaps(numSwapsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastball_cpp(inputList, numSwaps));
    return rcpp_result_gen;
END_RCPP
}
// sample_matrix
IntegerVector sample_matrix(NumericMatrix x);
RcppExport SEXP _backbone_sample_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_matrix(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_backbone_fastball_cpp", (DL_FUNC) &_backbone_fastball_cpp, 2},
    {"_backbone_sample_matrix", (DL_FUNC) &_backbone_sample_matrix, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_backbone(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
